### ISSUE TITLE
[JENKINS-35129] After upgrade of 1.650 to 2.6 - unable to configure jobs

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-14#5540]
<p><a href="http://10.101.6.243:8080/view/Misc/job/Node-Keep-Alive/configure" class="external-link" target="_blank" rel="nofollow noopener">http://10.101.6.243:8080/view/Misc/job/Node-Keep-Alive/configure</a></p>

<pre>
May 25, 2016 10:05:38 AM hudson.ExpressionFactory2$JexlExpression evaluate
WARNING: Caught exception evaluating: d.helpFile in /view/Misc/job/Node-Keep-Alive/configure. Reason: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.commons.jexl.util.PropertyExecutor.execute(PropertyExecutor.java:125)
at org.apache.commons.jexl.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:314)

Caused by: java.lang.NoClassDefFoundError: hudson/tasks/Ant
at java.lang.<span class="code-object">Class</span>.getDeclaredMethods0(Native Method)
at java.lang.<span class="code-object">Class</span>.privateGetDeclaredMethods(<span class="code-object">Class</span>.java:2625)
at java.lang.<span class="code-object">Class</span>.getDeclaredMethods(<span class="code-object">Class</span>.java:1868)
at org.kohsuke.stapler.ClassDescriptor.findMethods(ClassDescriptor.java:148)
at org.kohsuke.stapler.ClassDescriptor.<init>(ClassDescriptor.java:84)
at org.kohsuke.stapler.MetaClass.buildDispatchers(MetaClass.java:106)
at org.kohsuke.stapler.MetaClass.<init>(MetaClass.java:94)
at org.kohsuke.stapler.WebApp.getMetaClass(WebApp.java:203)
at org.kohsuke.stapler.jelly.groovy.GroovyFacet.createRequestDispatcher(GroovyFacet.java:106)
at org.kohsuke.stapler.RequestImpl.getView(RequestImpl.java:257)
at org.kohsuke.stapler.RequestImpl.getView(RequestImpl.java:252)
at hudson.model.Descriptor.getHelpFile(Descriptor.java:742)
at hudson.model.Descriptor.getHelpFile(Descriptor.java:724)
at hudson.model.Descriptor.getHelpFile(Descriptor.java:713)
... 167 more
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Ant
at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
... 181 more
</pre>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/alex_carr.png" title="alex_carr's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=alex_carr">alex_carr</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-35129" target="_blank">After upgrade of 1.650 to 2.6 - unable to configure jobs</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2016-06-01T16:12:54+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-11-14
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p><a href="http://10.101.6.243:8080/view/Misc/job/Node-Keep-Alive/configure" class="external-link" target="_blank" rel="nofollow noopener">http://10.101.6.243:8080/view/Misc/job/Node-Keep-Alive/configure</a></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">May 25, 2016 10:05:38 AM hudson.ExpressionFactory2$JexlExpression evaluate
WARNING: Caught exception evaluating: d.helpFile in /view/Misc/job/Node-Keep-Alive/configure. Reason: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.commons.jexl.util.PropertyExecutor.execute(PropertyExecutor.java:125)
        at org.apache.commons.jexl.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:314)

Caused by: java.lang.NoClassDefFoundError: hudson/tasks/Ant
        at java.lang.<span class="code-object">Class</span>.getDeclaredMethods0(Native Method)
        at java.lang.<span class="code-object">Class</span>.privateGetDeclaredMethods(<span class="code-object">Class</span>.java:2625)
        at java.lang.<span class="code-object">Class</span>.getDeclaredMethods(<span class="code-object">Class</span>.java:1868)
        at org.kohsuke.stapler.ClassDescriptor.findMethods(ClassDescriptor.java:148)
        at org.kohsuke.stapler.ClassDescriptor.&lt;init&gt;(ClassDescriptor.java:84)
        at org.kohsuke.stapler.MetaClass.buildDispatchers(MetaClass.java:106)
        at org.kohsuke.stapler.MetaClass.&lt;init&gt;(MetaClass.java:94)
        at org.kohsuke.stapler.WebApp.getMetaClass(WebApp.java:203)
        at org.kohsuke.stapler.jelly.groovy.GroovyFacet.createRequestDispatcher(GroovyFacet.java:106)
        at org.kohsuke.stapler.RequestImpl.getView(RequestImpl.java:257)
        at org.kohsuke.stapler.RequestImpl.getView(RequestImpl.java:252)
        at hudson.model.Descriptor.getHelpFile(Descriptor.java:742)
        at hudson.model.Descriptor.getHelpFile(Descriptor.java:724)
        at hudson.model.Descriptor.getHelpFile(Descriptor.java:713)
        ... 167 more
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Ant
        at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
        at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
        at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
        at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
        ... 181 more
</pre>
</div></div></pre>
</details>
</details>
<details><summary><i>1 attachment</i></summary>

- [catalina.out](https://issues.jenkins.io/secure/attachment/32803/catalina.out)
</details>
