### ISSUE TITLE
[JENKINS-15120] Minimize round trips for slave class loading

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-14#1544]
<p>Currently each attempt to load a class in a remote JVM makes a round-trip request to the master, which over a laggy network can make class loading quite slow, thus adding considerable overhead to the first build on a new slave.</p>

<p>Two possible solutions have been put forward.</p>

<h2><a name="Optimisticprefetch"></a>Optimistic prefetch</h2>

<p>The idea: when sending a class file to be loaded, scan its bytecode for other statically linked classes which have not yet been loaded, and send those along as well. In the common case that a network of classes is loaded around the same time, this would avoid some round trips.</p>

<h3><a name="Details"></a>Details</h3>

<p>The first part is for one side to keep track of what classes the other side has already loaded (into which class loader), which is basically memorizing the response from <tt>IClassLoader.fetch2</tt>.</p>

<p>The second part is to add <tt>Collection<ClassFile> IClassLoader.fetch3</tt> that works like <tt>fetch2</tt>, except it will also parse the class, figure out some of the referenced classes that are not yet loaded by the other side, then send them along.</p>

<p>Those prefetched class files would need to be remembered by <tt>RemoteClassLoader</tt> so that when those are actually requested it can load a class in the right classloader without calling back <tt>RemoteClassLoader.proxy</tt>. (Assuming there are no side effects, it could also eagerly call <tt>RemoteClassLoader.loadClassFile</tt> on the prefetched classes.)</p>

<p>The remoting layer supports talking to an earlier version of the remoting layer. We do this by a bitmask in <tt>Capability</tt>, so this needs one more bit defined there. There is no point in tracking the classes the other side has loaded if the other side will never call <tt>fetch3</tt>.</p>

<h2><a name="Bulktransfer"></a>Bulk transfer</h2>

<p>Send entire JAR files at a time, rather than individual classes; can wind up transferring more than is needed, but the reduction in latency is probably worth it. Since arbitrary class loader graphs might be in use, not just a flat classpath, some custom code needs to be run <em>remotely</em> which will implement the class loader delegation model without hitting the network for each class.</p>

<h3><a name="Details"></a>Details</h3>

<p>An API sketch:</p>

<pre>
<span class="code-keyword">class </span>Channel {
  void setClassLoaderTrafficCop(TrafficCop cop);
}
<span class="code-keyword">interface</span> TrafficCop {
  <span class="code-comment">/** <span class="code-keyword">do</span> I know/control/own <span class="code-keyword">this</span> classloader? */</span>
  <span class="code-object">boolean</span> controls(<span class="code-object">ClassLoader</span> cl);
  Set<JarFile> getJarFilesOf(<span class="code-object">ClassLoader</span> cl);
  RemotePartOfTrafficCop getRemotePart();
}
<span class="code-keyword">class </span>JarFile {
  <span class="code-object">String</span> checksum();
  InputStream data();
}
<span class="code-comment">/** runs in remote agent */</span>
<span class="code-keyword">interface</span> RemotePartOfTrafficCop <span class="code-keyword">implements</span> Serializable {
  <span class="code-comment">/** given a <span class="code-keyword">class/</span>resource and an originating loader, what is the defining loader? */</span>
  RemoteClassLoader trafficControl(RemoteClassLoader origin, <span class="code-object">String</span> resourceName);
}
</pre>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-15120" target="_blank">Minimize round trips for slave class loading</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kohsuke">kohsuke</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2013-06-25T22:26:05+00:00
<li><b>votes</b>: 2
<li><b>watchers</b>: 12
<li><b>imported</b>: 2025-11-14
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Currently each attempt to load a class in a remote JVM makes a round-trip request to the master, which over a laggy network can make class loading quite slow, thus adding considerable overhead to the first build on a new slave.</p>

<p>Two possible solutions have been put forward.</p>

<h2><a name="Optimisticprefetch"></a>Optimistic prefetch</h2>

<p>The idea: when sending a class file to be loaded, scan its bytecode for other statically linked classes which have not yet been loaded, and send those along as well. In the common case that a network of classes is loaded around the same time, this would avoid some round trips.</p>

<h3><a name="Details"></a>Details</h3>

<p>The first part is for one side to keep track of what classes the other side has already loaded (into which class loader), which is basically memorizing the response from <tt>IClassLoader.fetch2</tt>.</p>

<p>The second part is to add <tt>Collection&lt;ClassFile&gt; IClassLoader.fetch3</tt> that works like <tt>fetch2</tt>, except it will also parse the class, figure out some of the referenced classes that are not yet loaded by the other side, then send them along.</p>

<p>Those prefetched class files would need to be remembered by <tt>RemoteClassLoader</tt> so that when those are actually requested it can load a class in the right classloader without calling back <tt>RemoteClassLoader.proxy</tt>. (Assuming there are no side effects, it could also eagerly call <tt>RemoteClassLoader.loadClassFile</tt> on the prefetched classes.)</p>

<p>The remoting layer supports talking to an earlier version of the remoting layer. We do this by a bitmask in <tt>Capability</tt>, so this needs one more bit defined there. There is no point in tracking the classes the other side has loaded if the other side will never call <tt>fetch3</tt>.</p>

<h2><a name="Bulktransfer"></a>Bulk transfer</h2>

<p>Send entire JAR files at a time, rather than individual classes; can wind up transferring more than is needed, but the reduction in latency is probably worth it. Since arbitrary class loader graphs might be in use, not just a flat classpath, some custom code needs to be run <em>remotely</em> which will implement the class loader delegation model without hitting the network for each class.</p>

<h3><a name="Details"></a>Details</h3>

<p>An API sketch:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">class </span>Channel {
  void setClassLoaderTrafficCop(TrafficCop cop);
}
<span class="code-keyword">interface</span> TrafficCop {
  <span class="code-comment">/** <span class="code-keyword">do</span> I know/control/own <span class="code-keyword">this</span> classloader? */</span>
  <span class="code-object">boolean</span> controls(<span class="code-object">ClassLoader</span> cl);
  Set&lt;JarFile&gt; getJarFilesOf(<span class="code-object">ClassLoader</span> cl);
  RemotePartOfTrafficCop getRemotePart();
}
<span class="code-keyword">class </span>JarFile {
  <span class="code-object">String</span> checksum();
  InputStream data();
}
<span class="code-comment">/** runs in remote agent */</span>
<span class="code-keyword">interface</span> RemotePartOfTrafficCop <span class="code-keyword">implements</span> Serializable {
  <span class="code-comment">/** given a <span class="code-keyword">class/</span>resource and an originating loader, what is the defining loader? */</span>
  RemoteClassLoader trafficControl(RemoteClassLoader origin, <span class="code-object">String</span> resourceName);
}
</pre>
</div></div></pre>
</details>
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>jglick's <a href="https://issues.jenkins.io/browse/JENKINS-15120?focusedId=171589&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-171589">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p><a href="https://github.com/jenkinsci/remoting/pull/10" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/remoting/pull/10</a></p>
</pre>
</details>

</details>
<p><a href="https://github.com/jenkinsci/remoting/pull/10" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/remoting/pull/10</a></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>jglick's <a href="https://issues.jenkins.io/browse/JENKINS-15120?focusedId=179178&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-179178">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Using <tt>mock-slave</tt> with 10ms latency and building a multimodule Maven project in current trunk I get</p>

<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>Loading Type</th>
<th class='confluenceTh'>Time (s)</th>
<th class='confluenceTh'>Count</th>
</tr>
<tr>
<td class='confluenceTd'>Classes</td>
<td class='confluenceTd'>223.8</td>
<td class='confluenceTd'>2993</td>
</tr>
<tr>
<td class='confluenceTd'>Resources</td>
<td class='confluenceTd'>2.7</td>
<td class='confluenceTd'>23</td>
</tr>
</tbody></table>
</div>


<p>With <tt>prefetch-JENKINS&#45;15120</tt> from Jenkins core checked out (which pulls in a branch of the same name from <tt>remoting</tt>), this was</p>

<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>Loading Type</th>
<th class='confluenceTh'>Time (s)</th>
<th class='confluenceTh'>Count</th>
</tr>
<tr>
<td class='confluenceTd'>Classes</td>
<td class='confluenceTd'>165.5</td>
<td class='confluenceTd'>3361 (prefetch cache: 1651)</td>
</tr>
<tr>
<td class='confluenceTd'>Resources</td>
<td class='confluenceTd'>2.3</td>
<td class='confluenceTd'>26</td>
</tr>
</tbody></table>
</div>


<p>though timing is not exactly comparable since the branch currently enables rather verbose logging which slows down the connection.</p>
</pre>
</details>

</details>
<p>Using <tt>mock-slave</tt> with 10ms latency and building a multimodule Maven project in current trunk I get</p>

<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>Loading Type</th>
<th class='confluenceTh'>Time (s)</th>
<th class='confluenceTh'>Count</th>
</tr>
<tr>
<td class='confluenceTd'>Classes</td>
<td class='confluenceTd'>223.8</td>
<td class='confluenceTd'>2993</td>
</tr>
<tr>
<td class='confluenceTd'>Resources</td>
<td class='confluenceTd'>2.7</td>
<td class='confluenceTd'>23</td>
</tr>
</tbody></table>
</div>


<p>With <tt>prefetch-JENKINS&#45;15120</tt> from Jenkins core checked out (which pulls in a branch of the same name from <tt>remoting</tt>), this was</p>

<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>Loading Type</th>
<th class='confluenceTh'>Time (s)</th>
<th class='confluenceTh'>Count</th>
</tr>
<tr>
<td class='confluenceTd'>Classes</td>
<td class='confluenceTd'>165.5</td>
<td class='confluenceTd'>3361 (prefetch cache: 1651)</td>
</tr>
<tr>
<td class='confluenceTd'>Resources</td>
<td class='confluenceTd'>2.3</td>
<td class='confluenceTd'>26</td>
</tr>
</tbody></table>
</div>


<p>though timing is not exactly comparable since the branch currently enables rather verbose logging which slows down the connection.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>scm_issue_link's <a href="https://issues.jenkins.io/browse/JENKINS-15120?focusedId=179748&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-179748">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Code changed in jenkins
User: Kohsuke Kawaguchi
Path:
 changelog.html
 core/src/main/java/hudson/ClassicPluginStrategy.java
 maven-plugin/src/main/java/hudson/maven/Maven3Builder.java
 pom.xml
<a href="http://jenkins-ci.org/commit/jenkins/f7330d7a158eff6705706b1f812993a9b918c351" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/jenkins/f7330d7a158eff6705706b1f812993a9b918c351</a>
Log:
  <span class="error">&#91;FIXED JENKINS-15120&#93;</span></p>

<ul class="alternate" type="square">
	<li>integrated the newer release of remoting</li>
	<li>jar caching won't work with class file directory, so plugin
  WEB-INF/classes are now exploded as WEB-INF/lib/classes.jar
  (This should also solve the problem of slow plugin extraction in the
  presene of Anti-virus software on Windows.)</li>
	<li>because the structure of the exploded jar file has changed, I changed
  the up-to-date check timestamp file name to force re-extraction in
  existing installations.</li>
</ul>



<p>Compare: <a href="https://github.com/jenkinsci/jenkins/compare/b1f5d28f90ca...f7330d7a158e" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/compare/b1f5d28f90ca...f7330d7a158e</a></p>

</pre>
</details>

</details>
<p>Code changed in jenkins<br/>
User: Kohsuke Kawaguchi<br/>
Path:<br/>
 changelog.html<br/>
 core/src/main/java/hudson/ClassicPluginStrategy.java<br/>
 maven-plugin/src/main/java/hudson/maven/Maven3Builder.java<br/>
 pom.xml<br/>
<a href="http://jenkins-ci.org/commit/jenkins/f7330d7a158eff6705706b1f812993a9b918c351" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/jenkins/f7330d7a158eff6705706b1f812993a9b918c351</a><br/>
Log:<br/>
  <span class="error">&#91;FIXED JENKINS-15120&#93;</span></p>

<ul class="alternate" type="square">
	<li>integrated the newer release of remoting</li>
	<li>jar caching won't work with class file directory, so plugin<br/>
  WEB-INF/classes are now exploded as WEB-INF/lib/classes.jar<br/>
  (This should also solve the problem of slow plugin extraction in the<br/>
  presene of Anti-virus software on Windows.)</li>
	<li>because the structure of the exploded jar file has changed, I changed<br/>
  the up-to-date check timestamp file name to force re-extraction in<br/>
  existing installations.</li>
</ul>



<p>Compare: <a href="https://github.com/jenkinsci/jenkins/compare/b1f5d28f90ca...f7330d7a158e" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/compare/b1f5d28f90ca...f7330d7a158e</a></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>dogfood's <a href="https://issues.jenkins.io/browse/JENKINS-15120?focusedId=179749&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-179749">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Integrated in <span class="image-wrap" style=""><img src="http://ci.jenkins-ci.org/images/16x16/yellow.png" style="border: 0px solid black" /></span> <a href="http://ci.jenkins-ci.org/job/jenkins_main_trunk/2582/" class="external-link" target="_blank" rel="nofollow noopener">jenkins_main_trunk #2582</a>
     <span class="error">&#91;FIXED JENKINS-15120&#93;</span> (Revision f7330d7a158eff6705706b1f812993a9b918c351)</p>

<p>     Result = UNSTABLE
kohsuke : <a href="https://github.com/jenkinsci/jenkins/commit/f7330d7a158eff6705706b1f812993a9b918c351" class="external-link" target="_blank" rel="nofollow noopener">f7330d7a158eff6705706b1f812993a9b918c351</a>
Files : </p>
<ul>
	<li>maven-plugin/src/main/java/hudson/maven/Maven3Builder.java</li>
	<li>pom.xml</li>
	<li>core/src/main/java/hudson/ClassicPluginStrategy.java</li>
	<li>changelog.html</li>
</ul>

</pre>
</details>

</details>
<p>Integrated in <span class="image-wrap" style=""><img src="http://ci.jenkins-ci.org/images/16x16/yellow.png" style="border: 0px solid black" /></span> <a href="http://ci.jenkins-ci.org/job/jenkins_main_trunk/2582/" class="external-link" target="_blank" rel="nofollow noopener">jenkins_main_trunk #2582</a><br/>
     <span class="error">&#91;FIXED JENKINS-15120&#93;</span> (Revision f7330d7a158eff6705706b1f812993a9b918c351)</p>

<p>     Result = UNSTABLE<br/>
kohsuke : <a href="https://github.com/jenkinsci/jenkins/commit/f7330d7a158eff6705706b1f812993a9b918c351" class="external-link" target="_blank" rel="nofollow noopener">f7330d7a158eff6705706b1f812993a9b918c351</a><br/>
Files : </p>
<ul>
	<li>maven-plugin/src/main/java/hudson/maven/Maven3Builder.java</li>
	<li>pom.xml</li>
	<li>core/src/main/java/hudson/ClassicPluginStrategy.java</li>
	<li>changelog.html</li>
</ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>scm_issue_link's <a href="https://issues.jenkins.io/browse/JENKINS-15120?focusedId=179820&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-179820">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Code changed in jenkins
User: Kohsuke Kawaguchi
Path:
 src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
 src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java
<a href="http://jenkins-ci.org/commit/maven-hpi-plugin/603535119122e820751607812bb7d0bd3b8c3556" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/maven-hpi-plugin/603535119122e820751607812bb7d0bd3b8c3556</a>
Log:
  Modified to produce a jar file instead of WEB-INF/classes</p>

<p>Because of the prefetching change in remoting  (see <a href="https://issues.jenkins.io/browse/JENKINS-15120" title="Minimize round trips for slave class loading" class="issue-link" data-issue-key="JENKINS-15120"><del>JENKINS-15120</del></a>), it
is desirable now to produce class files in a jar file, not in a classes
directory, so that slaves can prefetch them and cache them efficiently.</p>


<p>Compare: <a href="https://github.com/jenkinsci/maven-hpi-plugin/compare/4d27f2880fa5...603535119122" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/maven-hpi-plugin/compare/4d27f2880fa5...603535119122</a></p>

</pre>
</details>

</details>
<p>Code changed in jenkins<br/>
User: Kohsuke Kawaguchi<br/>
Path:<br/>
 src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java<br/>
 src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java<br/>
<a href="http://jenkins-ci.org/commit/maven-hpi-plugin/603535119122e820751607812bb7d0bd3b8c3556" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/maven-hpi-plugin/603535119122e820751607812bb7d0bd3b8c3556</a><br/>
Log:<br/>
  Modified to produce a jar file instead of WEB-INF/classes</p>

<p>Because of the prefetching change in remoting  (see <a href="https://issues.jenkins.io/browse/JENKINS-15120" title="Minimize round trips for slave class loading" class="issue-link" data-issue-key="JENKINS-15120"><del>JENKINS-15120</del></a>), it<br/>
is desirable now to produce class files in a jar file, not in a classes<br/>
directory, so that slaves can prefetch them and cache them efficiently.</p>


<p>Compare: <a href="https://github.com/jenkinsci/maven-hpi-plugin/compare/4d27f2880fa5...603535119122" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/maven-hpi-plugin/compare/4d27f2880fa5...603535119122</a></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>hx_unbanned's <a href="https://issues.jenkins.io/browse/JENKINS-15120?focusedId=179829&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-179829">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Would this work affect freestyle projects using ant / nant / batch builds?</p>
</pre>
</details>

</details>
<p>Would this work affect freestyle projects using ant / nant / batch builds?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>drulli's <a href="https://issues.jenkins.io/browse/JENKINS-15120?focusedId=180308&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-180308">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Seems that this new feature breaks class loading of the findbugs plug-in, see <a href="https://issues.jenkins.io/browse/JENKINS-18405" title="Findbugs plugin unable to run on slaves with 1.519" class="issue-link" data-issue-key="JENKINS-18405"><del>JENKINS-18405</del></a> and <a href="https://issues.jenkins.io/browse/JENKINS-18394" title="IncompatibleClassChangeError after upgrade to 1.519" class="issue-link" data-issue-key="JENKINS-18394"><del>JENKINS-18394</del></a> for details...</p>
</pre>
</details>

</details>
<p>Seems that this new feature breaks class loading of the findbugs plug-in, see <a href="https://issues.jenkins.io/browse/JENKINS-18405" title="Findbugs plugin unable to run on slaves with 1.519" class="issue-link" data-issue-key="JENKINS-18405"><del>JENKINS-18405</del></a> and <a href="https://issues.jenkins.io/browse/JENKINS-18394" title="IncompatibleClassChangeError after upgrade to 1.519" class="issue-link" data-issue-key="JENKINS-18394"><del>JENKINS-18394</del></a> for details...</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>kutzi's <a href="https://issues.jenkins.io/browse/JENKINS-15120?focusedId=180412&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-180412">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Maybe also the cause of <a href="https://issues.jenkins.io/browse/JENKINS-18401" title="java.lang.NoClassDefFoundError: hudson/maven/MavenReporter" class="issue-link" data-issue-key="JENKINS-18401"><del>JENKINS-18401</del></a></p>
</pre>
</details>

</details>
<p>Maybe also the cause of <a href="https://issues.jenkins.io/browse/JENKINS-18401" title="java.lang.NoClassDefFoundError: hudson/maven/MavenReporter" class="issue-link" data-issue-key="JENKINS-18401"><del>JENKINS-18401</del></a></p>

**Comment by jenkins-infra-bot** [comment]
<i>[Originally related to: <a href="https://github.com/timja-org/jenkins-gh-issues-poc-11-14/issues?q=in%3Atitle%20JENKINS-16261">JENKINS-16261</a>]</i>

**Comment by jenkins-infra-bot** [comment]
<i>[Originally related to: <a href="https://github.com/timja-org/jenkins-gh-issues-poc-11-14/issues?q=in%3Atitle%20JENKINS-18525">JENKINS-18525</a>]</i>

**Comment by jenkins-infra-bot** [comment]
<i>[Originally related to: <a href="https://github.com/timja-org/jenkins-gh-issues-poc-11-14/issues?q=in%3Atitle%20JENKINS-18528">JENKINS-18528</a>]</i>
