### ISSUE TITLE
[JENKINS-6054] Class Not Found Exceptions

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-14#7950]
<p>Whenever we need to restart tomcat hudson comes with a series of class not found exceptions when starting a maven job. Either hudson.EnvVars or hudson.Main - the classes are definetly in the classpach (checked WEB-INF/lib/hudson-core). After a number of restarts of tomcat (3-10) it sometimes works again.</p>

<p>FATAL: Could not initialize class hudson.EnvVars<br/>
java.lang.NoClassDefFoundError: Could not initialize class hudson.EnvVars<br/>
	at hudson.model.Computer.getEnvironment(Computer.java:736)<br/>
	at hudson.model.Run.getEnvironment(Run.java:1648)<br/>
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:663)<br/>
	at hudson.maven.MavenModuleSetBuild.getEnvironment(MavenModuleSetBuild.java:128)<br/>
	at hudson.maven.MavenModuleSetBuild$RunnerImpl.doRun(MavenModuleSetBuild.java:384)<br/>
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:416)<br/>
	at hudson.model.Run.run(Run.java:1243)<br/>
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:304)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:122)</p>

<p>OR </p>

<p>FATAL: hudson/Main (wrong name: Main)<br/>
java.lang.NoClassDefFoundError: hudson/Main (wrong name: Main)<br/>
	at java.lang.ClassLoader.defineClass1(Native Method)<br/>
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)<br/>
	at java.lang.ClassLoader.defineClass(ClassLoader.java:616)<br/>
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)<br/>
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)<br/>
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)<br/>
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)<br/>
	at java.security.AccessController.doPrivileged(Native Method)<br/>
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)<br/>
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)<br/>
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)<br/>
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)<br/>
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1302)<br/>
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1233)<br/>
	at hudson.EnvVars.initMaster(EnvVars.java:223)<br/>
	at hudson.EnvVars.<clinit>(EnvVars.java:218)<br/>
	at hudson.model.Computer.getEnvironment(Computer.java:736)<br/>
	at hudson.model.Run.getEnvironment(Run.java:1648)<br/>
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:663)<br/>
	at hudson.maven.MavenModuleSetBuild.getEnvironment(MavenModuleSetBuild.java:128)<br/>
	at hudson.maven.MavenModuleSetBuild$RunnerImpl.doRun(MavenModuleSetBuild.java:384)<br/>
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:416)<br/>
	at hudson.model.Run.run(Run.java:1243)<br/>
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:304)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:122)</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ajuffinger">ajuffinger</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-6054" target="_blank">Class Not Found Exceptions</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2011-03-21T12:03:54+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-11-14
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Whenever we need to restart tomcat hudson comes with a series of class not found exceptions when starting a maven job. Either hudson.EnvVars or hudson.Main - the classes are definetly in the classpach (checked WEB-INF/lib/hudson-core). After a number of restarts of tomcat (3-10) it sometimes works again.</p>

<p>FATAL: Could not initialize class hudson.EnvVars
java.lang.NoClassDefFoundError: Could not initialize class hudson.EnvVars
	at hudson.model.Computer.getEnvironment(Computer.java:736)
	at hudson.model.Run.getEnvironment(Run.java:1648)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:663)
	at hudson.maven.MavenModuleSetBuild.getEnvironment(MavenModuleSetBuild.java:128)
	at hudson.maven.MavenModuleSetBuild$RunnerImpl.doRun(MavenModuleSetBuild.java:384)
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:416)
	at hudson.model.Run.run(Run.java:1243)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:304)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:122)</p>

<p>OR </p>

<p>FATAL: hudson/Main (wrong name: Main)
java.lang.NoClassDefFoundError: hudson/Main (wrong name: Main)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1302)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1233)
	at hudson.EnvVars.initMaster(EnvVars.java:223)
	at hudson.EnvVars.&lt;clinit&gt;(EnvVars.java:218)
	at hudson.model.Computer.getEnvironment(Computer.java:736)
	at hudson.model.Run.getEnvironment(Run.java:1648)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:663)
	at hudson.maven.MavenModuleSetBuild.getEnvironment(MavenModuleSetBuild.java:128)
	at hudson.maven.MavenModuleSetBuild$RunnerImpl.doRun(MavenModuleSetBuild.java:384)
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:416)
	at hudson.model.Run.run(Run.java:1243)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:304)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:122)</p>

</pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Linux Redhat AS x86_64, Java JDK, Clean fresh deployment hudson.war (1.352)</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>mirumpf's <a href="https://issues.jenkins.io/browse/JENKINS-6054?focusedId=139434&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-139434">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>I am facing the same issue after upgrading from Hudson 1.357 to 1.362:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">A         taco-ws/.settings/org.eclipse.jdt.core.prefs
A         taco-ws/.settings/org.eclipse.jst.j2ee.ejb.annotations.xdoclet.prefs
A         taco-ws/.settings/org.eclipse.wst.common.project.facet.core.xml
A         taco-ws/.settings/org.eclipse.jst.common.project.facet.core.prefs
A         taco-ws/.settings/org.eclipse.wst.common.component
A         taco-ws/.settings/org.eclipse.wst.html.core.prefs
At revision 7244
no change <span class="code-keyword">for</span> https:<span class="code-comment">//.../trunk since the previous build
</span>FATAL: Could not initialize <span class="code-keyword">class </span>hudson.EnvVars
java.lang.NoClassDefFoundError: Could not initialize <span class="code-keyword">class </span>hudson.EnvVars
	at hudson.model.Computer.getEnvironment(Computer.java:736)
	at hudson.model.Run.getEnvironment(Run.java:1651)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:682)
	at hudson.tasks.Ant.perform(Ant.java:134)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
	at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:601)
	at hudson.model.Build$RunnerImpl.build(Build.java:174)
	at hudson.model.Build$RunnerImpl.doRun(Build.java:138)
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:416)
	at hudson.model.Run.run(Run.java:1253)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:124)
</pre>
</div></div>

<p>The Hudson has been started with the following command line:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">root      5330     1 20 16:30 ?        00:03:49 /usr/share/jdk1.6.0_20/bin/java -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.util.logging.config.file=/export/build/tomcat/conf/logging.properties -Dappserver.home=/export/build/tomcat -Dappserver.base=/export/build/tomcat -Dartifactory.home=/export/build/artifactory -Xms512m -Xmx512m -XX:MaxPermSize=128m -DHUDSON_HOME=/export/build/hudson -Dhttp.proxyHost=www-5g.dienste.t-systems.com -Dhttp.proxyPort=80 -Djava.endorsed.dirs=/export/build/tomcat/endorsed -classpath :/export/build/tomcat/bin/bootstrap.jar -Dcatalina.base=/export/build/tomcat -Dcatalina.home=/export/build/tomcat -Djava.io.tmpdir=/export/build/tomcat/temp org.apache.catalina.startup.Bootstrap start
</pre>
</div></div>


<p>Restarting the tomcat server (just once) successfully resolved the issue!</p>

<p>The new Tomcat process has been started like this:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">root      5945     1 34 16:50 pts/1    00:03:52 /usr/share/jdk1.6.0_20/bin/java -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.util.logging.config.file=/export/build/tomcat/conf/logging.properties -Dappserver.home=/export/build/tomcat -Dappserver.base=/export/build/tomcat -Dartifactory.home=/export/build/artifactory -Xms512m -Xmx512m -XX:MaxPermSize=128m -DHUDSON_HOME=/export/build/hudson -Dhttp.proxyHost=www-5g.dienste.t-systems.com -Dhttp.proxyPort=80 -Djava.endorsed.dirs=/export/build/tomcat/endorsed -classpath :/export/build/tomcat/bin/bootstrap.jar -Dcatalina.base=/export/build/tomcat -Dcatalina.home=/export/build/tomcat -Djava.io.tmpdir=/export/build/tomcat/temp org.apache.catalina.startup.Bootstrap start
</pre>
</div></div>
</pre>
</details>

</details>
<p>I am facing the same issue after upgrading from Hudson 1.357 to 1.362:</p>


<pre>
A taco-ws/.settings/org.eclipse.jdt.core.prefs
A taco-ws/.settings/org.eclipse.jst.j2ee.ejb.annotations.xdoclet.prefs
A taco-ws/.settings/org.eclipse.wst.common.project.facet.core.xml
A taco-ws/.settings/org.eclipse.jst.common.project.facet.core.prefs
A taco-ws/.settings/org.eclipse.wst.common.component
A taco-ws/.settings/org.eclipse.wst.html.core.prefs
At revision 7244
no change <span class="code-keyword">for</span> https:<span class="code-comment">//.../trunk since the previous build
</span>FATAL: Could not initialize <span class="code-keyword">class </span>hudson.EnvVars
java.lang.NoClassDefFoundError: Could not initialize <span class="code-keyword">class </span>hudson.EnvVars
	at hudson.model.Computer.getEnvironment(Computer.java:736)
	at hudson.model.Run.getEnvironment(Run.java:1651)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:682)
	at hudson.tasks.Ant.perform(Ant.java:134)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
	at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:601)
	at hudson.model.Build$RunnerImpl.build(Build.java:174)
	at hudson.model.Build$RunnerImpl.doRun(Build.java:138)
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:416)
	at hudson.model.Run.run(Run.java:1253)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:124)
</pre>

<p>The Hudson has been started with the following command line:</p>

<pre>
root      5330     1 20 16:30 ?00:03:49 /usr/share/jdk1.6.0_20/bin/java -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.util.logging.config.file=/export/build/tomcat/conf/logging.properties -Dappserver.home=/export/build/tomcat -Dappserver.base=/export/build/tomcat -Dartifactory.home=/export/build/artifactory -Xms512m -Xmx512m -XX:MaxPermSize=128m -DHUDSON_HOME=/export/build/hudson -Dhttp.proxyHost=www-5g.dienste.t-systems.com -Dhttp.proxyPort=80 -Djava.endorsed.dirs=/export/build/tomcat/endorsed -classpath :/export/build/tomcat/bin/bootstrap.jar -Dcatalina.base=/export/build/tomcat -Dcatalina.home=/export/build/tomcat -Djava.io.tmpdir=/export/build/tomcat/temp org.apache.catalina.startup.Bootstrap start
</pre>


<p>Restarting the tomcat server (just once) successfully resolved the issue!</p>

<p>The new Tomcat process has been started like this:</p>

<pre>
root      5945     1 34 16:50 pts/1    00:03:52 /usr/share/jdk1.6.0_20/bin/java -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.util.logging.config.file=/export/build/tomcat/conf/logging.properties -Dappserver.home=/export/build/tomcat -Dappserver.base=/export/build/tomcat -Dartifactory.home=/export/build/artifactory -Xms512m -Xmx512m -XX:MaxPermSize=128m -DHUDSON_HOME=/export/build/hudson -Dhttp.proxyHost=www-5g.dienste.t-systems.com -Dhttp.proxyPort=80 -Djava.endorsed.dirs=/export/build/tomcat/endorsed -classpath :/export/build/tomcat/bin/bootstrap.jar -Dcatalina.base=/export/build/tomcat -Dcatalina.home=/export/build/tomcat -Djava.io.tmpdir=/export/build/tomcat/temp org.apache.catalina.startup.Bootstrap start
</pre>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/sogabe.png" title="sogabe's avatar" /> sogabe's <a href="https://issues.jenkins.io/browse/JENKINS-6054?focusedId=147016&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-147016">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>I can not reproduce. If reproduced, reopen the ticket.</p>
</pre>
</details>

</details>
<p>I can not reproduce. If reproduced, reopen the ticket.</p>
